/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package codezine.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULTI = 4;
  public int JJTDIVISION = 5;
  public int JJTSTRING = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Multi",
    "Division",
    "String",
  };
}
/* JavaCC - OriginalChecksum=3b3757bf8e3c2909fa83967b5f636b26 (do not edit this line) */
