/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package codezine.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULTI = 4;
  public int JJTDIVISION = 5;
  public int JJTSTRING = 6;
  public int JJTINTEGER = 7;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Multi",
    "Division",
    "String",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=2632d0c69068edcf823f103d76e91d31 (do not edit this line) */
