/* Generated By:JavaCC: Do not edit this line. ExprParserVisitor.java Version 6.0_1 */
package codezine.expr.parser;

public interface ExprParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTDivision node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=fc8d707340aa15734195741031790263 (do not edit this line) */
