/* Generated By:JavaCC: Do not edit this line. ExprParserDefaultVisitor.java Version 6.0_1 */
package codezine.expr.parser;

public class ExprParserDefaultVisitor implements ExprParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSub node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMulti node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDivision node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTString node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=146f6a7a5bfcfd897675d4b027e448b7 (do not edit this line) */
